name = "validator"
uuid = "537a2c72-97c0-4036-a644-bd9cb164770b"
authors = ["Anup Joseph <anup20joseph@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]